### ISSUE TITLE
script works fine in every vps platform unles you choose hetzner.de

### ISSUE THREAD

**Issue by fgarcia-humanoide** [Yenthe666/InstallScript#148]
Hallo,

The script works fine in every vps platform unles you choose hetzner. I've tried it in ubuntu 18.04 with odoo 11 CE.

Of course it is a hetzner.de problem.

¿Anyone knows how to solve it?

Thank you.

**Comment by fgarcia-humanoide** [comment]
ModuleNotFoundError: No module named 'PIL'

and a lot of other errors. odoo cannot start.

**Comment by Yenthe666** [comment]
Does it work if you do
`pip3 install -R requirements.txt` (which is in the odoo directory)?

**Comment by Yenthe666** [comment]
Also, any chance you can test with a concept branch I have? See https://github.com/Yenthe666/InstallScript/tree/12-requirements

**Comment by fgarcia-humanoide** [comment]
Thank you for answering,

After installing , I use this script. So all requirements are installed

t/odoo/account-financial-reporting
pip3 install -r requirements.txt


cd /opt/odoo/account-financial-tools
pip3 install -r requirements.txt

cd /opt/odoo/bank-statement-import
pip3 install -r requirements.txt


cd /opt/odoo/community-data-files
pip3 install -r requirements.txt

cd /opt/odoo/l10n-spain
pip3 install -r requirements.txt

cd /opt/odoo/odoo-server
pip3 install -r requirements.txt

cd /opt/odoo/purchase-workflow
pip3 install -r requirements.txt


cd /opt/odoo/queue
pip3 install -r requirements.txt


cd /opt/odoo/reporting-engine
pip3 install -r requirements.txt

cd /opt/odoo/server-tools
pip3 install -r requirements.txt

cd /opt/odoo/web
pip3 install -r requirements.txt

**Comment by Yenthe666** [comment]
Why don't you take the main requirements defined in the root directory though? See https://github.com/odoo/odoo/blob/12.0/requirements.txt
They contain all requirements at once, for the whole Odoo stack. There is no needed to take all the other requirement files manually?

**Comment by fgarcia-humanoide** [comment]
I have installed all requirements, even 
 https://github.com/odoo/odoo/blob/12.0/requirements.txt  for version 11

Service odoo does not start

I started it manually with

python3 /opt/odoo/odoo-server/odoo-bin -c /etc/odoo-server.conf

and some errors appear, if i correct the error , andother error appears in an infinite loop

------

File "/opt/odoo/odoo-server/odoo/tools/image.py", line 7, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

------

ModuleNotFoundError: No module named 'psutil'

I have used the script with success many times , but in hetzner an vulture not working

![yenthe](https://user-images.githubusercontent.com/7599709/54878164-14bbfa00-4e29-11e9-8270-c9a7d8364b36.JPG)

**Comment by Yenthe666** [comment]
It looks like some dependencies are missing for those builds. Exactly which version from Ubuntu is it?

**Comment by fgarcia-humanoide** [comment]
18:04

**Comment by Yenthe666** [comment]
I wonder if they use personalised / minimalized Ubuntu 18.04 builds as those requirements are available on a default 18.04.

**Comment by izubak** [comment]
https://github.com/Yenthe666/InstallScript/issues/130#issuecomment-437655224
Did you try this? It worked for me.

**Comment by eversatis** [comment]
This scrip is also not working on Google Cloud Platform VM.

**Comment by Yenthe666** [comment]
@frankmiao2015 could you give https://github.com/Yenthe666/InstallScript/tree/12-requirements a try too please? Does that work?
What does your log say?

**Comment by odooconcept** [comment]
I installed this 12-requirements script in AWS Ubuntu 18.04 with no sucess. Neither did it work the other v.12 script in GCP or AWS.
I looked for the log file but there is none.

I never had these issues before. The script has worked perfecty until recently. Something has changed in Odoo code.

**Comment by Yenthe666** [comment]
@odooconcept run it from the terminal (`./odoo-bin -c /etc/odoo-server.conf`). This will force a logfile creation and the traceback of the issue. Can you post that back please?

**Comment by odooconcept** [comment]
Actually I was finally able to install it. It was an issue related to hardware limitations of server at line:

`Running setup.py install for lxml`

It stayed there a long time and finally gave an error message

I increased RAM and solved.

Thanks!

**Comment by Yenthe666** [comment]
Ahh I see, thanks for the feedback.

**Comment by jayo2005** [comment]
Same issues on AWS. Ive tried on 5 or 6 different servers from AWS and the same issues. I had to manually install
lxml
PyPDF2
image
There was a lot more I had to manually install too ill take note the next time.

No odoo log file created.

Same issue on Ubuntu server 16.04  & 18.04

**Comment by Yenthe666** [comment]
@jayoo2005 did you also test the 12-requirements branch? Did this also give you issues?

**Comment by jayo2005** [comment]
@Yenthe666  No this was an Odoo 11 install. I have another install to do tomorrow on AWS for Odoo 11 also. I can test if you like

**Comment by Yenthe666** [comment]
I currently only have an alternative branch in place for V12. You're free to change the V11 so it uses requirements.txt to test it for V11 though.

**Comment by Ajilis** [comment]
> ./odoo-bin -c /etc/odoo-server.conf

root@vultr:/odoo/odoo-server# ./odoo-bin -c /etc/odoo-server.conf
Traceback (most recent call last):
  File "./odoo-bin", line 5, in <module>
    import odoo
  File "/odoo/odoo-server/odoo/__init__.py", line 73, in <module>
    import babel
ModuleNotFoundError: No module named 'babel'

**Comment by jayo2005** [comment]
I think `sudo pip3 install babel` will fix that. But there will be loads more missing also. I am going to try the requirements.txt for v12 soon. I will let you know

**Comment by Yenthe666** [comment]
Thanks! The requirements branch should solve it as in `requirements.txt` you have the Babel requirement (`Babel==2.3.4`) set.

**Comment by jayo2005** [comment]
Yes works with requirements from odoo 12 but I still have issues with the log file.
I install Ubuntu with a user called jason.
Only thing I change on the script is the password.
I also get OperationalError: FATAL: role “root” does not exist 

```
To fix I add
1- Open Terminal and enter => sudo su postgres
2- Enter password for postgres System user (if it is necessary)
3- createuser root -s( I also create user call jason)
4- psql template1
5- alter role root with password ‘yourpassword’;
6- \q
7- exit
8- service odoo restart
```
```
running ./odoo-bin -c /etc/odoo-server.conf  I get following error
odoo-bin: error: The config file '/etc/odoo-server.conf' selected with -c/--config doesn't exist or is not readable, use -s/--save if you want to generate it
```
sudo service odoo-server start works -  and odoo runs but with no log

./odoo-bin works with log and no errors

Should I be adding more to the script? It takes me longer to fix these than doing a manual install.

Any idea how to get Logs working?

**Comment by Yenthe666** [comment]
I've merged all changes into stable at https://github.com/Yenthe666/InstallScript/commit/b9727fd7870efdcad561e07ba9bc478b3775c3f7
@jayo2005 what you're showing seems to be misuse of the script or security rights. Are you sure that you're following the installation procedure at https://github.com/Yenthe666/InstallScript/tree/12.0#installation-procedure ?

**Comment by jayo2005** [comment]
@Yenthe666  Yes I follow the procedure.
I change OE_SUPERADMIN  and leave everything else default.

When installing Ubuntu should the user be odoo instead of jason?
It is definitely a permission issue

**Comment by Yenthe666** [comment]
The username shouldn't matter honestly, as long as you do not name it "root" or your main user it should work fine.

**Comment by jayo2005** [comment]
`sudo chown odoo:odoo -R /var/log/odoo/odoo-server.log` fixed it. For some reason the user & group was root root

**Comment by fgarcia-humanoide** [comment]
ModuleNotFoundError: No module named 'psutil'

and psutil is imposible to install

**Comment by fgarcia-humanoide** [comment]
root@odoo:/opt/odoo/odoo-server# pip3 install psutil
Collecting psutil
  Using cached https://files.pythonhosted.org/packages/c6/c1/beed5e4eaa1345901b595048fab1c85aee647ea0fc02d9e8bf9aceb81078/psutil-5.6.2.tar.gz
Building wheels for collected packages: psutil
  Building wheel for psutil (setup.py) ... error
  ERROR: Complete output from command /usr/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-phy9d2ac/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-cjag4t6w --python-tag cp36:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/psutil
  copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_psosx.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/__init__.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_psaix.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_common.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_compat.py -> build/lib.linux-x86_64-3.6/psutil
  copying psutil/_psposix.py -> build/lib.linux-x86_64-3.6/psutil
  creating build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_memory_leaks.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/runner.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.6/psutil/tests
  copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.6/psutil/tests
  running build_ext
  building 'psutil._psutil_linux' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/psutil
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=562 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/usr/include/python3.6m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.6/psutil/_psutil_common.o
  unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for psutil
  Running setup.py clean for psutil
Failed to build psutil
Installing collected packages: psutil
  Running setup.py install for psutil ... error
    ERROR: Complete output from command /usr/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-phy9d2ac/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wwcfkw72/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/psutil
    copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psosx.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/__init__.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psaix.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_common.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_compat.py -> build/lib.linux-x86_64-3.6/psutil
    copying psutil/_psposix.py -> build/lib.linux-x86_64-3.6/psutil
    creating build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_memory_leaks.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/runner.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.6/psutil/tests
    copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.6/psutil/tests
    running build_ext
    building 'psutil._psutil_linux' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/psutil
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=562 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/usr/include/python3.6m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.6/psutil/_psutil_common.o
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/usr/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-phy9d2ac/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wwcfkw72/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-phy9d2ac/psutil/

**Comment by Yenthe666** [comment]
How on exactly which OS are you doing this? It is declared in the requirements.txt from Odoo too (https://github.com/odoo/odoo/blob/12.0/requirements.txt#L24) and it should work fine.

**Comment by Yenthe666** [comment]
I've also discussed this with somebody at Odoo Experience and they confirmed that Hetzner strips down the linux images so hard that a lot of basic packages are even stripped out. I'm not going to bother with fixing this for just one hosting provider. If somebody finds the missing packages and proposes a PR I'll look at it.
